package privatetypes

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"testing"

	dnsv2 "codeberg.org/miekg/dns"
)

func TestAzureAlias(t *testing.T) {
	y := &AZUREALIAS{
		Hdr:       dnsv2.Header{Name: "example.org.", Class: dnsv2.ClassINET},
		AliasType: "A",
		Target:    "example.com.",
	}
	rry, err := dnsv2.New(y.String())
	if err != nil {
		t.Fatal(err)
	}
	if rry.String() != y.String() {
		t.Fatalf("AZURE_ALIAS string presentations should be identical:\n%s\n%s", rry.String(), y.String())
	}
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
