package privatetypes

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"fmt"
	"strconv"

	dnsv2 "codeberg.org/miekg/dns"
	dnsutilv2 "codeberg.org/miekg/dns/dnsutil"
	"github.com/DNSControl/dnscontrol/v4/pkg/mustbe"
	privatetypesrdata "github.com/DNSControl/dnscontrol/v4/pkg/privatetypes/rdata"
)

// BUNNY_DNS_PZ

func init() {
	Register(TypeBUNNYDNSPZ, "BUNNY_DNS_PZ", func() dnsv2.RR { return new(BUNNYDNSPZ) }, privatetypesrdata.MakeBUNNYDNSPZ)
}

const TypeBUNNYDNSPZ = uint16(65287)

type BUNNYDNSPZ struct {
	Hdr dnsv2.Header

	privatetypesrdata.BUNNYDNSPZ
	// PullZoneID           int64
}

// Typer interface.

func (rr *BUNNYDNSPZ) Type() uint16 { return TypeBUNNYDNSPZ }

// RR interface.

func (rr *BUNNYDNSPZ) Header() *dnsv2.Header { return &rr.Hdr }
func (rr *BUNNYDNSPZ) Len() int {
	return rr.Hdr.Len() + rr.Data().Len()
}
func (rr *BUNNYDNSPZ) Data() dnsv2.RDATA {
	return privatetypesrdata.BUNNYDNSPZ{PullZoneID: rr.PullZoneID}
}
func (rr *BUNNYDNSPZ) Clone() dnsv2.RR {
	return &BUNNYDNSPZ{
		Hdr: rr.Hdr,
		BUNNYDNSPZ: privatetypesrdata.BUNNYDNSPZ{
			PullZoneID: rr.PullZoneID,
		}}
}
func (rr *BUNNYDNSPZ) String() string {
	return (rr.Header().Name + "\t" +
		strconv.FormatInt(int64(rr.Header().TTL), 10) + "\t" +
		dnsutilv2.ClassToString(rr.Header().Class) + "\tBUNNY_DNS_PZ\t" + rr.Data().String())
}

// Parse makes an RDATA for this type using the tokens from dnsv2's parser.
func (rr *BUNNYDNSPZ) Parse(tokens []string, s string) error {
	args := TokensToArgs(tokens)
	if len(args) != 1 {
		return fmt.Errorf("BUNNY_DNS_PZ requires exactly 1 arguments, got %d: %v", len(args), args)
	}
	rr.PullZoneID = mustbe.Int64(args[0])
	return nil
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
