package privatetypes

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"testing"

	dnsv2 "codeberg.org/miekg/dns"
)

func TestCloudflareapiSingleRedirect(t *testing.T) {
	y := &CLOUDFLAREAPISINGLEREDIRECT{
		Hdr:    dnsv2.Header{Name: "example.org.", Class: dnsv2.ClassINET},
		SRName: "first_rule",
		Code:   301,
		SRWhen: "when_string",
		SRThen: "then_string",
	}
	rry, err := dnsv2.New(y.String())
	if err != nil {
		t.Fatal(err)
	}
	if rry.String() != y.String() {
		t.Fatalf("CLOUDFLAREAPI_SINGLE_REDIRECT string presentations should be identical:\n%s\n%s", rry.String(), y.String())
	}
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
