package privatetypes

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"testing"

	dnsv2 "codeberg.org/miekg/dns"
)

func TestImportTransform(t *testing.T) {
	y := &IMPORTTRANSFORM{
		Hdr:            dnsv2.Header{Name: "example.org.", Class: dnsv2.ClassINET},
		TransformTable: "1.1.1.0 ~ 1.1.1.100 ~ 4.4.4.100 ~",
		TTL:            123,
		SuffixStrip:    "com",
		TargetDomain:   "example.com",
	}
	rry, err := dnsv2.New(y.String())
	if err != nil {
		t.Fatal(err)
	}
	if rry.String() != y.String() {
		t.Fatalf("IMPORT_TRANSFORM string presentations should be identical:\n%s\n%s", rry.String(), y.String())
	}
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
