package privatetypes

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"fmt"
	"strconv"

	dnsv2 "codeberg.org/miekg/dns"
	dnsutilv2 "codeberg.org/miekg/dns/dnsutil"
	"github.com/DNSControl/dnscontrol/v5/pkg/mustbe"
	privatetypesrdata "github.com/DNSControl/dnscontrol/v5/pkg/privatetypes/rdata"
)

// MIKROTIK_FORWARDER

func init() {
	Register(TypeMIKROTIKFORWARDER, "MIKROTIK_FORWARDER", func() dnsv2.RR { return new(MIKROTIKFORWARDER) }, privatetypesrdata.MakeMIKROTIKFORWARDER)
}

const TypeMIKROTIKFORWARDER = uint16(65321)

type MIKROTIKFORWARDER struct {
	Hdr dnsv2.Header

	privatetypesrdata.MIKROTIKFORWARDER
	// Target               string
}

// Typer interface.

func (rr *MIKROTIKFORWARDER) Type() uint16 { return TypeMIKROTIKFORWARDER }

// RR interface.

func (rr *MIKROTIKFORWARDER) Header() *dnsv2.Header { return &rr.Hdr }
func (rr *MIKROTIKFORWARDER) Len() int {
	return rr.Hdr.Len() + rr.Data().Len()
}
func (rr *MIKROTIKFORWARDER) Data() dnsv2.RDATA {
	return privatetypesrdata.MIKROTIKFORWARDER{Target: rr.Target}
}
func (rr *MIKROTIKFORWARDER) Clone() dnsv2.RR {
	return &MIKROTIKFORWARDER{
		Hdr:    rr.Hdr,
		Target: rr.Target}
}
func (rr *MIKROTIKFORWARDER) String() string {
	return (rr.Header().Name + "\t" +
		strconv.FormatInt(int64(rr.Header().TTL), 10) + "\t" +
		dnsutilv2.ClassToString(rr.Header().Class) + "\tMIKROTIK_FORWARDER\t" + rr.Data().String())
}

// Parse makes an RDATA for this type using the tokens from dnsv2's parser.
func (rr *MIKROTIKFORWARDER) Parse(tokens []string, s string) error {
	args := TokensToArgs(tokens)
	if len(args) != 1 {
		return fmt.Errorf("MIKROTIK_FORWARDER requires exactly 1 arguments, got %d: %v", len(args), args)
	}
	rr.Target = mustbe.RawString(args[0])
	return nil
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
