package privatetypes

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"testing"

	dnsv2 "codeberg.org/miekg/dns"
	privatetypesrdata "github.com/DNSControl/dnscontrol/v5/pkg/privatetypes/rdata"
)

func TestMikrotikForwarder(t *testing.T) {
	y := &MIKROTIKFORWARDER{
		Hdr: dnsv2.Header{Name: "example.org.", Class: dnsv2.ClassINET},
		MIKROTIKFORWARDER: privatetypesrdata.MIKROTIKFORWARDER{
			Target: "1.1.1.1,8.8.8.8",
		},
	}
	rry, err := dnsv2.New(y.String())
	if err != nil {
		t.Fatal(err)
	}
	if rry.String() != y.String() {
		t.Fatalf("MIKROTIK_FORWARDER string presentations should be identical:\n%s\n%s", rry.String(), y.String())
	}
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
