package privatetypesrdata

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"fmt"
	"strings"

	dnsv2 "codeberg.org/miekg/dns"
	"github.com/DNSControl/dnscontrol/v5/pkg/mustbe"
	"github.com/DNSControl/dnscontrol/v5/pkg/txtutil"
)

type CFWORKERROUTE struct {
	When string
	Then string
}

func (rd CFWORKERROUTE) Len() int {
	return len(rd.String())
}

func (rd CFWORKERROUTE) String() string {
	parts := make([]string, 0, 2)
	parts = append(parts, txtutil.ZoneifyString(rd.When))
	parts = append(parts, txtutil.ZoneifyString(rd.Then))
	return strings.Join(parts, " ")
}

func MakeCFWORKERROUTE(origin string, _ map[string]string, args ...any) (dnsv2.RDATA, error) {
	mustbe.ValidArgs(args)
	if len(args) != 2 {
		return nil, fmt.Errorf("CF_WORKER_ROUTE expects 2 arguments, got %d: %+v", len(args), args)
	}
	return CFWORKERROUTE{
		When: mustbe.RawString(args[0]),
		Then: mustbe.RawString(args[1]),
	}, nil
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
