package privatetypesrdata

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"fmt"
	"strings"

	dnsv2 "codeberg.org/miekg/dns"
	"github.com/DNSControl/dnscontrol/v4/pkg/mustbe"
	"github.com/DNSControl/dnscontrol/v4/pkg/txtutil"
)

type LUA struct {
	LuaType    string
	LuaPayload string
}

func (rd LUA) Len() int {
	return len(rd.String())
}

func (rd LUA) String() string {
	parts := make([]string, 0, 2)
	parts = append(parts, txtutil.ZoneifyString(rd.LuaType))
	parts = append(parts, txtutil.ZoneifyString(rd.LuaPayload))
	return strings.Join(parts, " ")
}

func MakeLUA(origin string, _ map[string]string, args ...any) (dnsv2.RDATA, error) {
	mustbe.ValidArgs(args)
	if len(args) != 2 {
		return nil, fmt.Errorf("LUA expects 2 arguments, got %d: %+v", len(args), args)
	}
	return LUA{
		LuaType:    mustbe.RawString(args[0]),
		LuaPayload: mustbe.RawString(args[1]),
	}, nil
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
