package privatetypesrdata

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"fmt"
	"strings"

	dnsv2 "codeberg.org/miekg/dns"
	"github.com/DNSControl/dnscontrol/v5/pkg/mustbe"
	"github.com/DNSControl/dnscontrol/v5/pkg/nrc"
	"github.com/DNSControl/dnscontrol/v5/pkg/txtutil"
)

type URL struct {
	Location string
}

func (rd URL) Len() int {
	return len(rd.String())
}

func (rd URL) String() string {
	parts := make([]string, 0, 1)
	parts = append(parts, txtutil.ZoneifyString(rd.Location))
	return strings.Join(parts, " ")
}

func MakeURL(origin string, _ map[string]string, _ nrc.Flags, args ...any) (dnsv2.RDATA, error) {
	mustbe.ValidArgs(args)
	if len(args) != 1 {
		return nil, fmt.Errorf("URL expects 1 arguments, got %d: %+v", len(args), args)
	}
	return URL{
		Location: mustbe.RawString(args[0]),
	}, nil
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
