package privatetypesrdata

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"fmt"

	dnsv2 "codeberg.org/miekg/dns"
	"github.com/DNSControl/dnscontrol/v5/pkg/mustbe"
	"github.com/DNSControl/dnscontrol/v5/pkg/nrc"
)

type NETLIFY struct {
}

func (rd NETLIFY) Len() int {
	return 0
}

func (rd NETLIFY) String() string {
	return ""
}

func MakeNETLIFY(origin string, _ map[string]string, _ nrc.Flags, args ...any) (dnsv2.RDATA, error) {
	mustbe.ValidArgs(args)
	if len(args) != 0 {
		return nil, fmt.Errorf("NETLIFY expects 0 arguments, got %d: %+v", len(args), args)
	}
	return NETLIFY{}, nil
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
