package privatetypesrdata

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"fmt"
	"strings"

	dnsv2 "codeberg.org/miekg/dns"
	"github.com/DNSControl/dnscontrol/v5/pkg/mustbe"
	"github.com/DNSControl/dnscontrol/v5/pkg/nrc"
	"github.com/DNSControl/dnscontrol/v5/pkg/txtutil"
)

type IMPORTTRANSFORM struct {
	TransformTable string
	TTL            uint16
	SuffixStrip    string
	TargetDomain   string
}

func (rd IMPORTTRANSFORM) Len() int {
	return len(rd.String())
}

func (rd IMPORTTRANSFORM) String() string {
	parts := make([]string, 0, 4)
	parts = append(parts, txtutil.ZoneifyString(rd.TransformTable))
	parts = append(parts, fmt.Sprintf("%d", rd.TTL))
	parts = append(parts, txtutil.ZoneifyString(rd.SuffixStrip))
	parts = append(parts, txtutil.ZoneifyString(rd.TargetDomain))
	return strings.Join(parts, " ")
}

func MakeIMPORTTRANSFORM(origin string, _ map[string]string, _ nrc.Flags, args ...any) (dnsv2.RDATA, error) {
	mustbe.ValidArgs(args)
	if len(args) != 4 {
		return nil, fmt.Errorf("IMPORT_TRANSFORM expects 4 arguments, got %d: %+v", len(args), args)
	}
	return IMPORTTRANSFORM{
		TransformTable: mustbe.RawString(args[0]),
		TTL:            mustbe.Uint16(args[1]),
		SuffixStrip:    mustbe.RawString(args[2]),
		TargetDomain:   mustbe.RawString(args[3]),
	}, nil
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
