// Code generated by astype_generate.go; DO NOT EDIT.

package models

import (
	dnsrdatav2 "codeberg.org/miekg/dns/rdata"
	privatetypesrdata "github.com/DNSControl/dnscontrol/v5/pkg/privatetypes/rdata"
)

func (rc *RecordConfig) AsA() dnsrdatav2.A {
	return rc.GetRDATA().(dnsrdatav2.A)
}

func (rc *RecordConfig) AsAAAA() dnsrdatav2.AAAA {
	return rc.GetRDATA().(dnsrdatav2.AAAA)
}

func (rc *RecordConfig) AsADGUARDHOMEAAAAPASSTHROUGH() privatetypesrdata.ADGUARDHOMEAAAAPASSTHROUGH {
	return rc.GetRDATA().(privatetypesrdata.ADGUARDHOMEAAAAPASSTHROUGH)
}

func (rc *RecordConfig) AsADGUARDHOMEAPASSTHROUGH() privatetypesrdata.ADGUARDHOMEAPASSTHROUGH {
	return rc.GetRDATA().(privatetypesrdata.ADGUARDHOMEAPASSTHROUGH)
}

func (rc *RecordConfig) AsAFSDB() dnsrdatav2.AFSDB {
	return rc.GetRDATA().(dnsrdatav2.AFSDB)
}

func (rc *RecordConfig) AsAKAMAICDN() privatetypesrdata.AKAMAICDN {
	return rc.GetRDATA().(privatetypesrdata.AKAMAICDN)
}

func (rc *RecordConfig) AsAKAMAITLC() privatetypesrdata.AKAMAITLC {
	return rc.GetRDATA().(privatetypesrdata.AKAMAITLC)
}

func (rc *RecordConfig) AsALIAS() privatetypesrdata.ALIAS {
	return rc.GetRDATA().(privatetypesrdata.ALIAS)
}

func (rc *RecordConfig) AsAVC() dnsrdatav2.TXT {
	return rc.GetRDATA().(dnsrdatav2.TXT)
}

func (rc *RecordConfig) AsAZUREALIAS() privatetypesrdata.AZUREALIAS {
	return rc.GetRDATA().(privatetypesrdata.AZUREALIAS)
}

func (rc *RecordConfig) AsBUNNYDNSPZ() privatetypesrdata.BUNNYDNSPZ {
	return rc.GetRDATA().(privatetypesrdata.BUNNYDNSPZ)
}

func (rc *RecordConfig) AsBUNNYDNSRDR() privatetypesrdata.BUNNYDNSRDR {
	return rc.GetRDATA().(privatetypesrdata.BUNNYDNSRDR)
}

func (rc *RecordConfig) AsCAA() dnsrdatav2.CAA {
	return rc.GetRDATA().(dnsrdatav2.CAA)
}

func (rc *RecordConfig) AsCDNSKEY() dnsrdatav2.DNSKEY {
	return rc.GetRDATA().(dnsrdatav2.DNSKEY)
}

func (rc *RecordConfig) AsCDS() dnsrdatav2.DS {
	return rc.GetRDATA().(dnsrdatav2.DS)
}

func (rc *RecordConfig) AsCERT() dnsrdatav2.CERT {
	return rc.GetRDATA().(dnsrdatav2.CERT)
}

func (rc *RecordConfig) AsCFWORKERROUTE() privatetypesrdata.CFWORKERROUTE {
	return rc.GetRDATA().(privatetypesrdata.CFWORKERROUTE)
}

func (rc *RecordConfig) AsCLA() dnsrdatav2.TXT {
	return rc.GetRDATA().(dnsrdatav2.TXT)
}

func (rc *RecordConfig) AsCLOUDFLAREAPISINGLEREDIRECT() privatetypesrdata.CLOUDFLAREAPISINGLEREDIRECT {
	return rc.GetRDATA().(privatetypesrdata.CLOUDFLAREAPISINGLEREDIRECT)
}

func (rc *RecordConfig) AsCLOUDNSWR() privatetypesrdata.CLOUDNSWR {
	return rc.GetRDATA().(privatetypesrdata.CLOUDNSWR)
}

func (rc *RecordConfig) AsCNAME() dnsrdatav2.CNAME {
	return rc.GetRDATA().(dnsrdatav2.CNAME)
}

func (rc *RecordConfig) AsCSYNC() dnsrdatav2.CSYNC {
	return rc.GetRDATA().(dnsrdatav2.CSYNC)
}

func (rc *RecordConfig) AsDELEG() dnsrdatav2.DELEG {
	return rc.GetRDATA().(dnsrdatav2.DELEG)
}

func (rc *RecordConfig) AsDELEGPARAM() dnsrdatav2.DELEG {
	return rc.GetRDATA().(dnsrdatav2.DELEG)
}

func (rc *RecordConfig) AsDHCID() dnsrdatav2.DHCID {
	return rc.GetRDATA().(dnsrdatav2.DHCID)
}

func (rc *RecordConfig) AsDLV() dnsrdatav2.DS {
	return rc.GetRDATA().(dnsrdatav2.DS)
}

func (rc *RecordConfig) AsDNAME() dnsrdatav2.DNAME {
	return rc.GetRDATA().(dnsrdatav2.DNAME)
}

func (rc *RecordConfig) AsDNSKEY() dnsrdatav2.DNSKEY {
	return rc.GetRDATA().(dnsrdatav2.DNSKEY)
}

func (rc *RecordConfig) AsDS() dnsrdatav2.DS {
	return rc.GetRDATA().(dnsrdatav2.DS)
}

func (rc *RecordConfig) AsDSYNC() dnsrdatav2.DSYNC {
	return rc.GetRDATA().(dnsrdatav2.DSYNC)
}

func (rc *RecordConfig) AsEID() dnsrdatav2.EID {
	return rc.GetRDATA().(dnsrdatav2.EID)
}

func (rc *RecordConfig) AsEUI48() dnsrdatav2.EUI48 {
	return rc.GetRDATA().(dnsrdatav2.EUI48)
}

func (rc *RecordConfig) AsEUI64() dnsrdatav2.EUI64 {
	return rc.GetRDATA().(dnsrdatav2.EUI64)
}

func (rc *RecordConfig) AsFRAME() privatetypesrdata.FRAME {
	return rc.GetRDATA().(privatetypesrdata.FRAME)
}

func (rc *RecordConfig) AsGID() dnsrdatav2.GID {
	return rc.GetRDATA().(dnsrdatav2.GID)
}

func (rc *RecordConfig) AsGPOS() dnsrdatav2.GPOS {
	return rc.GetRDATA().(dnsrdatav2.GPOS)
}

func (rc *RecordConfig) AsHINFO() dnsrdatav2.HINFO {
	return rc.GetRDATA().(dnsrdatav2.HINFO)
}

func (rc *RecordConfig) AsHIP() dnsrdatav2.HIP {
	return rc.GetRDATA().(dnsrdatav2.HIP)
}

func (rc *RecordConfig) AsHTTPS() dnsrdatav2.SVCB {
	return rc.GetRDATA().(dnsrdatav2.SVCB)
}

func (rc *RecordConfig) AsIMPORTTRANSFORM() privatetypesrdata.IMPORTTRANSFORM {
	return rc.GetRDATA().(privatetypesrdata.IMPORTTRANSFORM)
}

func (rc *RecordConfig) AsIPN() dnsrdatav2.IPN {
	return rc.GetRDATA().(dnsrdatav2.IPN)
}

func (rc *RecordConfig) AsISDN() dnsrdatav2.ISDN {
	return rc.GetRDATA().(dnsrdatav2.ISDN)
}

func (rc *RecordConfig) AsKEY() dnsrdatav2.DNSKEY {
	return rc.GetRDATA().(dnsrdatav2.DNSKEY)
}

func (rc *RecordConfig) AsKX() dnsrdatav2.KX {
	return rc.GetRDATA().(dnsrdatav2.KX)
}

func (rc *RecordConfig) AsL32() dnsrdatav2.L32 {
	return rc.GetRDATA().(dnsrdatav2.L32)
}

func (rc *RecordConfig) AsL64() dnsrdatav2.L64 {
	return rc.GetRDATA().(dnsrdatav2.L64)
}

func (rc *RecordConfig) AsLOC() dnsrdatav2.LOC {
	return rc.GetRDATA().(dnsrdatav2.LOC)
}

func (rc *RecordConfig) AsLP() dnsrdatav2.LP {
	return rc.GetRDATA().(dnsrdatav2.LP)
}

func (rc *RecordConfig) AsLUA() privatetypesrdata.LUA {
	return rc.GetRDATA().(privatetypesrdata.LUA)
}

func (rc *RecordConfig) AsMB() dnsrdatav2.MB {
	return rc.GetRDATA().(dnsrdatav2.MB)
}

func (rc *RecordConfig) AsMD() dnsrdatav2.MD {
	return rc.GetRDATA().(dnsrdatav2.MD)
}

func (rc *RecordConfig) AsMF() dnsrdatav2.MF {
	return rc.GetRDATA().(dnsrdatav2.MF)
}

func (rc *RecordConfig) AsMG() dnsrdatav2.MG {
	return rc.GetRDATA().(dnsrdatav2.MG)
}

func (rc *RecordConfig) AsMIKROTIKFORWARDER() privatetypesrdata.MIKROTIKFORWARDER {
	return rc.GetRDATA().(privatetypesrdata.MIKROTIKFORWARDER)
}

func (rc *RecordConfig) AsMIKROTIKFWD() privatetypesrdata.MIKROTIKFWD {
	return rc.GetRDATA().(privatetypesrdata.MIKROTIKFWD)
}

func (rc *RecordConfig) AsMINFO() dnsrdatav2.MINFO {
	return rc.GetRDATA().(dnsrdatav2.MINFO)
}

func (rc *RecordConfig) AsMR() dnsrdatav2.MR {
	return rc.GetRDATA().(dnsrdatav2.MR)
}

func (rc *RecordConfig) AsMX() dnsrdatav2.MX {
	return rc.GetRDATA().(dnsrdatav2.MX)
}

func (rc *RecordConfig) AsNAPTR() dnsrdatav2.NAPTR {
	return rc.GetRDATA().(dnsrdatav2.NAPTR)
}

func (rc *RecordConfig) AsNID() dnsrdatav2.NID {
	return rc.GetRDATA().(dnsrdatav2.NID)
}

func (rc *RecordConfig) AsNIMLOC() dnsrdatav2.NIMLOC {
	return rc.GetRDATA().(dnsrdatav2.NIMLOC)
}

func (rc *RecordConfig) AsNINFO() dnsrdatav2.NINFO {
	return rc.GetRDATA().(dnsrdatav2.NINFO)
}

func (rc *RecordConfig) AsNS() dnsrdatav2.NS {
	return rc.GetRDATA().(dnsrdatav2.NS)
}

func (rc *RecordConfig) AsNSAPPTR() dnsrdatav2.NSAPPTR {
	return rc.GetRDATA().(dnsrdatav2.NSAPPTR)
}

func (rc *RecordConfig) AsNSEC() dnsrdatav2.NSEC {
	return rc.GetRDATA().(dnsrdatav2.NSEC)
}

func (rc *RecordConfig) AsNSEC3() dnsrdatav2.NSEC3 {
	return rc.GetRDATA().(dnsrdatav2.NSEC3)
}

func (rc *RecordConfig) AsNSEC3PARAM() dnsrdatav2.NSEC3PARAM {
	return rc.GetRDATA().(dnsrdatav2.NSEC3PARAM)
}

func (rc *RecordConfig) AsNULL() dnsrdatav2.NULL {
	return rc.GetRDATA().(dnsrdatav2.NULL)
}

func (rc *RecordConfig) AsNXT() dnsrdatav2.NSEC {
	return rc.GetRDATA().(dnsrdatav2.NSEC)
}

func (rc *RecordConfig) AsOPENPGPKEY() dnsrdatav2.OPENPGPKEY {
	return rc.GetRDATA().(dnsrdatav2.OPENPGPKEY)
}

func (rc *RecordConfig) AsPORKBUNURLFWD() privatetypesrdata.PORKBUNURLFWD {
	return rc.GetRDATA().(privatetypesrdata.PORKBUNURLFWD)
}

func (rc *RecordConfig) AsPTR() dnsrdatav2.PTR {
	return rc.GetRDATA().(dnsrdatav2.PTR)
}

func (rc *RecordConfig) AsPX() dnsrdatav2.PX {
	return rc.GetRDATA().(dnsrdatav2.PX)
}

func (rc *RecordConfig) AsR53ALIAS() privatetypesrdata.R53ALIAS {
	return rc.GetRDATA().(privatetypesrdata.R53ALIAS)
}

func (rc *RecordConfig) AsRESINFO() dnsrdatav2.TXT {
	return rc.GetRDATA().(dnsrdatav2.TXT)
}

func (rc *RecordConfig) AsRKEY() dnsrdatav2.RKEY {
	return rc.GetRDATA().(dnsrdatav2.RKEY)
}

func (rc *RecordConfig) AsRP() dnsrdatav2.RP {
	return rc.GetRDATA().(dnsrdatav2.RP)
}

func (rc *RecordConfig) AsRRSIG() dnsrdatav2.RRSIG {
	return rc.GetRDATA().(dnsrdatav2.RRSIG)
}

func (rc *RecordConfig) AsRT() dnsrdatav2.RT {
	return rc.GetRDATA().(dnsrdatav2.RT)
}

func (rc *RecordConfig) AsSIG() dnsrdatav2.RRSIG {
	return rc.GetRDATA().(dnsrdatav2.RRSIG)
}

func (rc *RecordConfig) AsSMIMEA() dnsrdatav2.SMIMEA {
	return rc.GetRDATA().(dnsrdatav2.SMIMEA)
}

func (rc *RecordConfig) AsSOA() dnsrdatav2.SOA {
	return rc.GetRDATA().(dnsrdatav2.SOA)
}

func (rc *RecordConfig) AsSPF() dnsrdatav2.TXT {
	return rc.GetRDATA().(dnsrdatav2.TXT)
}

func (rc *RecordConfig) AsSRV() dnsrdatav2.SRV {
	return rc.GetRDATA().(dnsrdatav2.SRV)
}

func (rc *RecordConfig) AsSSHFP() dnsrdatav2.SSHFP {
	return rc.GetRDATA().(dnsrdatav2.SSHFP)
}

func (rc *RecordConfig) AsSVCB() dnsrdatav2.SVCB {
	return rc.GetRDATA().(dnsrdatav2.SVCB)
}

func (rc *RecordConfig) AsTA() dnsrdatav2.TA {
	return rc.GetRDATA().(dnsrdatav2.TA)
}

func (rc *RecordConfig) AsTALINK() dnsrdatav2.TALINK {
	return rc.GetRDATA().(dnsrdatav2.TALINK)
}

func (rc *RecordConfig) AsTKEY() dnsrdatav2.TKEY {
	return rc.GetRDATA().(dnsrdatav2.TKEY)
}

func (rc *RecordConfig) AsTLSA() dnsrdatav2.TLSA {
	return rc.GetRDATA().(dnsrdatav2.TLSA)
}

func (rc *RecordConfig) AsTSIG() dnsrdatav2.TSIG {
	return rc.GetRDATA().(dnsrdatav2.TSIG)
}

func (rc *RecordConfig) AsTXT() dnsrdatav2.TXT {
	return rc.GetRDATA().(dnsrdatav2.TXT)
}

func (rc *RecordConfig) AsUID() dnsrdatav2.UID {
	return rc.GetRDATA().(dnsrdatav2.UID)
}

func (rc *RecordConfig) AsUINFO() dnsrdatav2.UINFO {
	return rc.GetRDATA().(dnsrdatav2.UINFO)
}

func (rc *RecordConfig) AsURI() dnsrdatav2.URI {
	return rc.GetRDATA().(dnsrdatav2.URI)
}

func (rc *RecordConfig) AsURL() privatetypesrdata.URL {
	return rc.GetRDATA().(privatetypesrdata.URL)
}

func (rc *RecordConfig) AsURL301() privatetypesrdata.URL301 {
	return rc.GetRDATA().(privatetypesrdata.URL301)
}

func (rc *RecordConfig) AsWALLET() dnsrdatav2.TXT {
	return rc.GetRDATA().(dnsrdatav2.TXT)
}

func (rc *RecordConfig) AsX25() dnsrdatav2.X25 {
	return rc.GetRDATA().(dnsrdatav2.X25)
}

func (rc *RecordConfig) AsZONEMD() dnsrdatav2.ZONEMD {
	return rc.GetRDATA().(dnsrdatav2.ZONEMD)
}
